In [ ]:
from Phase_1.DataLoader import DataLoader
from Phase_1.DataValidator import DataValidator
from Phase_1.DataPreprocessor import DataPreprocessor
from Phase_1.OutlierHandler import OutlierHandler
file_path = "train.csv"
# file_path = "heart.csv"
# file_path_2 = "Data.xlsx"

data = DataLoader(file_path)
data.load()
data = data.get_data()
data

CSV file loaded successfully

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# val_data = DataValidator(data)
# val_data.check_nulls()

Null values found in 3 column(s).

{'Age': 177, 'Cabin': 687, 'Embarked': 2}

In [8]:
print(val_data.check_duplicates())
print(val_data.check_types())

No duplicate rows found.
0
Data types retrieved successfully.
{'PassengerId': 'int64', 'Survived': 'int64', 'Pclass': 'int64', 'Name': 'object', 'Sex': 'object', 'Age': 'float64', 'SibSp': 'int64', 'Parch': 'int64', 'Ticket': 'object', 'Fare': 'float64', 'Cabin': 'object', 'Embarked': 'object'}

In [9]:
val_data.report_issues()

Null values found in 3 column(s).
Data types retrieved successfully.
No duplicate rows found.

{'missing_values': {'Age': 177, 'Cabin': 687, 'Embarked': 2},
 'data_types': {'PassengerId': 'int64',
  'Survived': 'int64',
  'Pclass': 'int64',
  'Name': 'object',
  'Sex': 'object',
  'Age': 'float64',
  'SibSp': 'int64',
  'Parch': 'int64',
  'Ticket': 'object',
  'Fare': 'float64',
  'Cabin': 'object',
  'Embarked': 'object'},
 'duplicates': 0}

In [13]:
from Phase_1.DataPreprocessor import DataPreprocessor
preprocess = DataPreprocessor(data)
preprocess.handle_nulls()

Filled nulls in 'Age' with Median: 28.0.
Dropping column 'Cabin' due to high null ratio (77.10%).
Dropping rows with nulls in 'Embarked' (low ratio: 0.22%).

d:\git\depi\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:50: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [28]:
print("Before conversion:")
print(data[['Name', 'Sex', 'Age', 'Fare', 'Survived', 'Pclass']].dtypes)

Before conversion:
Name         object
Sex          object
Age         float64
Fare        float64
Survived      int64
Pclass        int64
dtype: object

In [ ]:
# schema-based conversion with more columns
test_schema = {
    'Survived': 'bool',
    'Pclass': 'category',
    'Fare': 'float32' 
}


preprocess.convert_types(schema=test_schema)

# dtypes after conversion
print("Data types after manual schema conversion:")
print(preprocess.get_clean_data()[['Survived', 'Pclass', 'Fare']].dtypes)

Data types after manual schema conversion:
Survived        bool
Pclass      category
Fare         float32
dtype: object

In [ ]:
# before conversion
print("Memory before:", data.memory_usage(deep=True).sum(), "bytes")


preprocess.convert_types(schema)

# after conversion
print("Memory after:", preprocess.get_clean_data().memory_usage(deep=True).sum(), "bytes")

Memory before: 292464 bytes
Memory after: 266178 bytes

In [15]:
preprocess.remove_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [30]:
preprocess.get_clean_data()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250000,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.283302,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925000,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.099998,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050000,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000000,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000000,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.450001,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000000,C
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750000,Q

In [13]:
import pandas as pd
from ydata_profiling import ProfileReport
from jinja2 import Template

class  ReportGenerator:
   """
    A class for generating Exploratory Data Analysis (EDA) reports.

    This class supports two modes of report generation:
    1. Manual mode: basic statistical and structural analysis.
    2. Auto mode: full automated profiling report using ydata_profiling.

    Attributes:
        data (pd.DataFrame): The dataset used for analysis.
    """
   def __init__(self,data:pd.DataFrame):
        """
        Initialize the ReportGenerator with a dataset.

        Args:
            data (pd.DataFrame): The input dataset for analysis.
        """
        self.data =data

   def summary_stats(self):
       """
        Compute descriptive statistics for numeric columns.

        Returns:
            pd.DataFrame: Summary statistics (mean, std, min, max, etc.).
       """
       return self.data.describe()
   

   def correlation_matrix(self):
        """
        Compute correlation matrix for numeric features.

        Returns:
            pd.DataFrame: Correlation matrix between numeric columns.
        """
        return self.data.corr(numeric_only=True)
   
   def missing_values(self):
        """
        Calculate missing values for each column.

        Returns:
            pd.Series: Count of missing values per column.
        """
        return self.data.isnull().sum()
   

   def manual_report(self, template_path="template.html", output_file="report.html"):
        """
        Generate a manual HTML EDA report using a Jinja2 template.

        This method:
        - Loads an external HTML template
        - Injects analysis results into the template
        - Saves the final report as an HTML file

        The report includes:
        - Summary statistics
        - Missing values analysis
        - Correlation matrix
        - Basic insights (e.g., column with most missing values)

        Args:
            template_path (str): Path to the HTML template file.
            output_file (str): Name of the output HTML report.

        Returns:
            str: Confirmation message indicating where the report was saved.

        Raises:
            FileNotFoundError: If the template file does not exist.
        """

        # Load template
        with open(template_path, "r", encoding="utf-8") as f:
            template = Template(f.read())

        # Prepare data
        summary_html = self.summary_stats().to_html()
        corr_html = self.correlation_matrix().to_html()

        missing_df = self.missing_values()
        missing_html = missing_df.to_frame("Missing Values").to_html()

        # Generate simple insights
        top_missing = missing_df.idxmax()
        top_missing_val = missing_df.max()

        # Render template
        html_content = template.render(
            summary=summary_html,
            correlation=corr_html,
            missing=missing_html,
            top_missing=top_missing,
            top_missing_val=top_missing_val
        )

        # Save output
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(html_content)

        return f"Manual report saved as {output_file}"


   def auto_report(self, file_name="report.html", explorative=True):
        """
        Generate an automated EDA report using ydata_profiling.

        Args:
            file_name (str): Output HTML file name.
            explorative (bool): If True, enables deep exploratory analysis.

        Returns:
            str: Confirmation message with saved file name.
        """
        profile = ProfileReport(self.data,explorative=explorative)
        profile.to_file(file_name)
        return f"Auto report saved as {file_name}"
            
   def generate_report(self, mode="manual", file_name="report.html"):
       """
        Generate an EDA report based on selected mode.

        Modes:
            - "manual": returns structured analysis as Python objects.
            - "auto": generates full HTML profiling report.

        Args:
            mode (str): Type of report ("manual" or "auto").
            file_name (str): Output file name for auto report.

        Returns:
            dict or str:
                - dict if mode="manual"
                - str message if mode="auto"

        Raises:
            ValueError: If mode is not "manual" or "auto".
        """
       if mode == "manual":
            return self.manual_report()
       
       elif mode == "auto":
            return self.auto_report()
       else :
            raise ValueError("mode must be either 'manual' or 'auto'")

In [7]:
import pandas as pd

df = pd.read_csv("train.csv")

report = ReportGenerator(df)

# manual
result = report.generate_report(mode="manual")
print(result)

# auto HTML report
report.generate_report(mode="auto", file_name="report.html")

{'Summary':        PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200  , 'Correlation':              PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225

                 Fare
PassengerId  0.012658
Survived     0.257307
Pclass      -0.549500
Age          0.096067
SibSp        0.159651
Parch        0.216225
Fare         1.000000  , 'Missing Values': PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64}

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:01<00:00, 10.30it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

'Auto report saved as report.html'

In [14]:
report = ReportGenerator(df)

report.manual_report("Phase_1/template.html", "final_report.html")

'Manual report saved as final_report.html'